# Dependencies
gems:             [jekyll-paginate]
markdown:         kramdown
highlighter:      rouge

# Force UTF-8:
encoding: UTF-8

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Recurring ideas
tagline:          'A blog about mathematics'
description:      'Math nerd doing math nerd things.'
url:              http://parksw3.github.io
baseurl:          /

author:
  name:           'Sang Woo Park'
  url:            

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/parksw3/parksw3.github.io
