# Dependencies
gems:             [jekyll-paginate]
markdown:         kramdown
highlighter:      rouge

# Force UTF-8:
encoding: UTF-8

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Needs a title
tagline:          'What is this?'
description:      'A blog about random things.'
url:              http://parksw3.github.io
baseurl:          /

author:
  name:           'Sang Woo Park'
  url:            

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/parksw3/parksw3.github.io
