# Dependencies
gems:             [jekyll-paginate]
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Hyde
tagline:          'Needs a title'
description:      'A blog about random things.'
url:              http://parksw3.github.io
baseurl:          /

author:
  name:           'Sang Woo Park'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/parksw3/parksw3.github.io
